# Generated by Django 4.2.7 on 2025-08-27 10:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Seva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "seva_type",
                    models.CharField(
                        choices=[
                            ("pratyaksha", "Pratyaksha Seva"),
                            ("paroksha", "Paroksha Seva"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "how_performed",
                    models.TextField(help_text="How the seva is performed"),
                ),
                (
                    "duration",
                    models.CharField(
                        help_text="Duration of the seva (e.g., 2 hours)", max_length=50
                    ),
                ),
                ("start_time", models.TimeField(help_text="When the seva starts")),
                ("end_time", models.TimeField(help_text="When the seva ends")),
                (
                    "base_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Base cost of the seva",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("currency", models.CharField(default="INR", max_length=3)),
                (
                    "temple_provides",
                    models.TextField(
                        help_text="Ingredients/items provided by the temple"
                    ),
                ),
                (
                    "devotee_brings",
                    models.TextField(help_text="Items that devotees need to bring"),
                ),
                (
                    "benefits",
                    models.TextField(help_text="Benefits of performing this seva"),
                ),
                (
                    "images",
                    models.JSONField(
                        blank=True, default=list, help_text="List of image URLs"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "max_participants",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum number of participants (null for unlimited)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Sevas",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SevaCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Seva Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SevaSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "cost_override",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Override cost for this specific date",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "temple_provides_override",
                    models.TextField(
                        blank=True,
                        help_text="Override temple provides for this specific date",
                    ),
                ),
                (
                    "devotee_brings_override",
                    models.TextField(
                        blank=True,
                        help_text="Override devotee brings for this specific date",
                    ),
                ),
                (
                    "benefits_override",
                    models.TextField(
                        blank=True, help_text="Override benefits for this specific date"
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(help_text="Start time for this specific date"),
                ),
                (
                    "end_time",
                    models.TimeField(help_text="End time for this specific date"),
                ),
                (
                    "max_participants",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum participants for this specific date",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_booked",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this schedule is already booked",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "seva",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="sevas.seva",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Seva Schedules",
                "ordering": ["date", "start_time"],
                "unique_together": {("seva", "date", "start_time")},
            },
        ),
        migrations.CreateModel(
            name="SevaBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booking_date", models.DateTimeField(auto_now_add=True)),
                ("scheduled_date", models.DateField()),
                ("scheduled_time", models.TimeField()),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=10)),
                ("payment_status", models.CharField(default="pending", max_length=20)),
                ("payment_method", models.CharField(blank=True, max_length=50)),
                ("transaction_id", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("special_requests", models.TextField(blank=True)),
                ("number_of_participants", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "seva_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="sevas.sevaschedule",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seva_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Seva Bookings",
                "ordering": ["-booking_date"],
            },
        ),
        migrations.AddField(
            model_name="seva",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sevas",
                to="sevas.sevacategory",
            ),
        ),
        migrations.AddField(
            model_name="seva",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_sevas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
